In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr) 

[[1 2 3]
 [4 5 6]]


In [8]:
a = np.array([1,2,3,1])

b = (a==1)

print(b)

[ True False False  True]


In [9]:
a = [1,2,3,1]

b = (a==1)

print(b)

False


In [11]:
from sklearn.base import BaseEstimator
class Never5Classifier(BaseEstimator):
    def fit(self, X, y=None):
        pass
    def predict(self, X):
        return np.zeros((len(X), 1), dtype=bool)

In [18]:
np.zeros((3,1),dtype=bool)

array([[False],
       [False],
       [False]])